
cpcode: 
	cp -rf chisel_design/ /mnt/d/gitlab/chisel_design/
	cp -rf verilog_sim/ /mnt/d/gitlab/chisel_design/
	cp -rf env.*	/mnt/d/gitlab/chisel_design
	cp -rf *.md	/mnt/d/gitlab/chisel_design

