all: clean cp 


clean:
	rm -rf generated/*/*.fir generated/*/*.json

cp:
	cp -rf ./generated/uart/Axi4LiteUartTop.v /mnt/d/prj/routine/daily/uart-chisel/rtl/

#delete the folders: generated and test_run_dir
all_clean:
	rm -rf generated test_run_dir


